export const CLUB_CREATE_REQUEST = 'CLUB_CREATE_REQUEST'
export const CLUB_CREATE_SUCCESS = 'CLUB_CREATE_SUCCESS'
export const CLUB_CREATE_FAIL = 'CLUB_CREATE_FAIL'


export const CLUB_LIST_REQUEST = 'CLUB_LIST_REQUEST'
export const CLUB_LIST_SUCCESS = 'CLUB_LIST_SUCCESS'
export const CLUB_LIST_FAIL = 'CLUB_LIST_FAIL'
