export const DISCOUNT_CREATE_REQUEST = 'DISCOUNT_CREATE_REQUEST'
export const DISCOUNT_CREATE_SUCCESS = 'DISCOUNT_CREATE_SUCCESS'
export const DISCOUNT_CREATE_FAIL = 'DISCOUNT_CREATE_FAIL'


export const DISCOUNT_LIST_REQUEST = 'DISCOUNT_LIST_REQUEST'
export const DISCOUNT_LIST_SUCCESS = 'DISCOUNT_LIST_SUCCESS'
export const DISCOUNT_LIST_FAIL = 'DISCOUNT_LIST_FAIL'
