export const MEMBERSHIP_CREATE_REQUEST = 'MEMBERSHIP_CREATE_REQUEST'
export const MEMBERSHIP_CREATE_SUCCESS = 'MEMBERSHIP_CREATE_SUCCESS'
export const MEMBERSHIP_CREATE_FAIL = 'MEMBERSHIP_CREATE_FAIL'


export const MEMBERSHIP_LIST_REQUEST = 'MEMBERSHIP_LIST_REQUEST'
export const MEMBERSHIP_LIST_SUCCESS = 'MEMBERSHIP_LIST_SUCCESS'
export const MEMBERSHIP_LIST_FAIL = 'MEMBERSHIP_LIST_FAIL'

