export const PAYMENTMETHOD_CREATE_REQUEST = 'PAYMENTMETHOD_CREATE_REQUEST'
export const PAYMENTMETHOD_CREATE_SUCCESS = 'PAYMENTMETHOD_CREATE_SUCCESS'
export const PAYMENTMETHOD_CREATE_FAIL = 'PAYMENTMETHOD__CREATE_FAIL'

export const PAYMENTMETHOD_LIST_REQUEST = 'PAYMENTMETHOD_LIST_REQUEST'
export const PAYMENTMETHOD_LIST_SUCCESS = 'PAYMENTMETHOD_LIST_SUCCESS'
export const PAYMENTMETHOD_LIST_FAIL = 'PAYMENTMETHOD_LIST_FAIL'

